### PR TITLE
2.2.0

### PR DESCRIPTION
**Pull request by briangonzalez**
A couple things to note here:

- `requireSqlite()` was unnecessary imo. To hand wave over this fact, I included `sqlite` as an actual dep and not an optional one.
- I moved some of the db-specific logic into a module. This may seem unnecessary now, but I am setting myself up to make the code more organized and ultimately more testable once it comes time to write some units.
- `getRecentChats` returns a promise which resolves to an array of chats. The default limit is 10.

### CODE REVIEW

**Comment by wtfaremyinitials** [comment]
Please make sure the new DB implementation opens `chat.db` as readonly. I'm not comfortable opening it as writable on the master branch due to caution of corrupting people's iMessage data.

**Comment by briangonzalez** [comment]
@wtfaremyinitials Let me figure out how to do that. Any other concerns?

**Comment by briangonzalez** [comment]
@wtfaremyinitials Good to go.

**Comment by briangonzalez** [comment]
@wtfaremyinitials  Good catches. I'll look shortly.

**Comment by briangonzalez** [comment]
I am going to cleanup the commits once you look over what I've done!

**Comment by wtfaremyinitials** [comment]
Looks good to me. Let me now when you're ready for me to merge it

**Comment by briangonzalez** [comment]
Alright, we're cleaned up.

**Comment by wtfaremyinitials** [comment]
🎉

**Pull request merged**
