### PR TITLE
Add ability to send files with absolute filepath

### PR DESCRIPTION
**Pull request by elliotaplant**
Updated readme to include `sendFile` method

### CODE REVIEW

**Comment by lights0123** [comment]
@wtfaremyinitials any timeline on when this will be merged?

**Comment by alectrocute** [comment]
@wtfaremyinitials Any chance you could merge this?

**Comment by wtfaremyinitials** [comment]
I'm crazy busy for the next couple weeks but I'll try to get around to it when I can. In the meantime you should be able to `npm install git+https://git@github.com/elliotaplant/osa-imessage.git` to get that version

**Comment by ttay24** [comment]
any update?

**Comment by alectrocute** [comment]
It works, and has no conflicts. @wtfaremyinitials hit that green button 🙏

**Comment by elliotaplant** [comment]
Bumping this since it's been about 6 years. @wtfaremyinitials , any chance you can merge this?

**Pull request closed without merging**
